@LegoTestSite_HostAddress = http://localhost:5161

###
GET {{LegoTestSite_HostAddress}}/SetGallery
Accept: application/json

###
GET {{LegoTestSite_HostAddress}}/SetDetails?setID=30707
Accept: application/json

###
GET {{LegoTestSite_HostAddress}}/SetDetailsNotesInfo?setID=30707
Accept: application/json

###
GET {{LegoTestSite_HostAddress}}/SetDetailsBagsInfo?setID=30707
Accept: application/json

###
GET {{LegoTestSite_HostAddress}}/Test/TestSetGallery
Accept: application/json

###
GET {{LegoTestSite_HostAddress}}/Test/TestSetDetails?setID=30707
Accept: application/json

###
GET {{LegoTestSite_HostAddress}}/Test/TestSetDetailsNotesInfo?setID=30707
Accept: application/json

###
GET {{LegoTestSite_HostAddress}}/Test/TestSetDetailsBagsInfo?setID=30707
Accept: application/json